-- ============================================================
-- 006_import_monday.sql
-- Importação de encomendas históricas do Monday.com.
-- Gerado automaticamente por scripts/import-monday.js
-- Executar no Supabase SQL Editor (uma única vez).
-- ============================================================

BEGIN;

-- joana pinto
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES (DEFAULT, 'joana pinto', 'whatsapp', 'joana.a.pinto@hotmail.com', '351967410007', '2026-05-23', 'casamento', NULL, NULL, 'ctt', 'Bouquet de noiva', 'ctt', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'sim', 1, 'google', NULL, NULL, 'entrega_flores_agendar', 335, '100_por_pagar', 0, 'na', NULL, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Diana Alexandra Salgueiro Simões
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('P0W6Y3Q8B2N7J5L1', 'Diana Alexandra Salgueiro Simões', 'whatsapp', 'diana_s_simoes@hotmail.com', '351915239555', '2026-04-27', 'casamento', NULL, NULL, 'recolha_evento', 'Bouquet de noiva', 'nao_sei', 'preto', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'google', NULL, NULL, 'flores_recebidas', 300, '30_pago', 0, 'na', 40, TRUE, NULL, NULL, 'na', 'na', NULL);

-- Joana Rita Brito Matos
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('H4V9S6Z2U7G1E5D8', 'Joana Rita Brito Matos', 'whatsapp', 'joanaritamatos@gmail.com', '351914851031', '2026-05-03', 'casamento', NULL, NULL, 'maos', 'Bouquet de noiva (Joana, Lavanda e Jasmin) com tulipas, hortênsias, eucalipto…', 'maos', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'vale_presente', NULL, '(Origem: Lavanda e Jasmin 🤍🌸)', 'entrega_agendada', 300, '100_pago', 30, 'parceiro_informado', 25, TRUE, NULL, NULL, 'na', 'na', NULL);

-- Maria João Santos Martins da Silva
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('1FG9K2B7D4S0M3P8', 'Maria João Santos Martins da Silva', 'whatsapp', 'm19j@outlook.pt', '46793556106', '2026-05-09', 'casamento', NULL, NULL, 'maos', 'Bouquet de noiva. Ainda não sei bem o tipo de flores mas peonias vão estar incluidas', 'maos', 'nao_sei', 'nao_sei', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'mais_info', NULL, NULL, NULL, NULL, NULL, 'outro', NULL, NULL, 'entrega_agendada', 300, '30_pago', 30, 'parceiro_informado', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Sara Neves David
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('L9K6R2T4F1N5M8C3', 'Sara Neves David', 'whatsapp', 'ndavid.sara@gmail.com', '351913516551', '2026-05-23', 'casamento', 'Sara e Roberto', NULL, 'maos', 'Bouquet de noiva', 'maos', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'vale_presente', NULL, NULL, 'entrega_agendada', 300, '100_pago', 0, 'na', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Rita Vieira Marques
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('H9J3K7L1M6N5P4R2', 'Rita Vieira Marques', 'whatsapp', 'ritavmarques@netcabo.pt', '351912240091', '2026-06-06', 'casamento', NULL, NULL, 'maos', 'Bouquet de noiva com flores silvestres e do campo.', 'maos', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'florista', 'Lavanda e Jasmin.', NULL, 'entrega_agendada', 300, '30_pago', 30, 'parceiro_informado', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Catarina Goufa Martins
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('E7F1A4D8G2S5Z9U3', 'Catarina Goufa Martins', 'whatsapp', 'catarinagoufamartins@hotmail.com', '351912693214', '2026-07-25', NULL, NULL, NULL, 'maos', NULL, 'maos', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'instagram', NULL, NULL, 'entrega_agendada', 300, '30_pago', 0, 'na', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Carla Santos
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('K8F9M2X5A1R4T7C3', 'Carla Santos', 'whatsapp', 'carla-santos1999@outlook.com', '352661771777', '2026-08-01', 'casamento', NULL, NULL, 'maos', 'Bridal bouquet with peonies', 'nao_sei', 'transparente', '50x70', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'casamentos_pt', NULL, NULL, 'entrega_agendada', 500, '30_pago', 0, 'na', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Kelly Juliff
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('C3M8N5F1T4R2L9K6', 'Kelly Juliff', 'whatsapp', 'kelly.juliff93@googlemail.com', '4407580730615', '2026-08-24', 'casamento', NULL, NULL, 'recolha_evento', 'Bridal bouquet', 'ctt', 'transparente', 'nao_sei', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'google', NULL, NULL, 'entrega_agendada', 300, '30_pago', 0, 'na', 110, TRUE, NULL, NULL, 'na', 'na', NULL);

-- Alissa Rodrigues
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('A2K9X2P5V1M8Z4Q3', 'Alissa Rodrigues', 'whatsapp', 'rodrigali80@gmail.com', '12036954155', '2027-08-07', 'casamento', 'Alissa e Mário', NULL, 'maos', 'Bouquet de noiva - rosas branca, gypsophilia, folhagem verde', 'nao_sei', 'transparente', '50x70', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'instagram', NULL, NULL, 'entrega_agendada', 500, '30_pago', 0, 'na', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Lauren Jennings
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('N3F8L2Q7T5R9X1KP', 'Lauren Jennings', 'email', 'lbj8rv@hotmail.com', '8613124721153', '2025-09-30', 'casamento', NULL, NULL, 'recolha_evento', 'Bridal bouquet', 'nao_sei', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'sim', 4, NULL, NULL, NULL, NULL, 'outro', NULL, NULL, 'a_compor_design', 660, '70_pago', 66, 'paga', 90, TRUE, NULL, NULL, 'na', 'na', NULL);

-- Dora Patrícia Dias Cardoso
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('A7M4K9Z2R6T1Q8LX', 'Dora Patrícia Dias Cardoso', 'whatsapp', 'dora-cardoso@hotmail.com', '351965215293', '2025-10-04', NULL, NULL, NULL, 'maos', NULL, 'maos', 'voces_a_escolher', 'nao_sei', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'mais_info', NULL, NULL, NULL, NULL, NULL, 'florista', NULL, 'Casamento vai ser na Figueira da Foz', 'flores_na_prensa', 300, '70_pago', 30, 'a_aguardar_resposta', 0, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Joana
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES (DEFAULT, 'Joana', 'whatsapp', 'naodeixouemail@gmail.com', '351962267646', '2025-08-02', 'casamento', 'Joana e Alexandre', NULL, 'ctt', 'rosas', NULL, 'transparente', '50x70', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, 'outro', NULL, NULL, 'quadro_recebido', 500, '100_pago', 0, 'na', 0, FALSE, 'F2B5R', '2026-12-01', 'nao_utilizado', 'deu_feedback', '2025-11-19');

-- Rita Lourenço Matos
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES ('F8K2L9Q7M4R1T6ZX', 'Rita Lourenço Matos', 'whatsapp', 'ritalourenco94@gmail.com', '351913856036', '2025-08-30', 'casamento', 'Rita e João', NULL, 'maos', NULL, 'maos', 'transparente', '30x40', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, 'outro', NULL, NULL, 'quadro_recebido', 300, '100_pago', 0, 'na', 0, FALSE, 'F2B6R1', '2027-04-30', 'nao_utilizado', 'ja_pedido', NULL);

-- Maria Inês Cachulo Damasceno
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES (DEFAULT, 'Maria Inês Cachulo Damasceno', 'whatsapp', 'ines.damasceno97@gmail.com', '351916967793', '2025-09-19', 'casamento', 'Adeline e Rui', NULL, 'maos', NULL, 'maos', 'transparente', '30x40', '{"options":["Joia ou medalha"],"notes":""}'::jsonb, 'nao', NULL, NULL, NULL, NULL, NULL, 'outro', NULL, NULL, 'quadro_recebido', 0, '100_por_pagar', 0, 'na', 0, FALSE, 'F2B5R2', '2027-01-31', 'nao_utilizado', 'ja_pedido', '2025-12-23');

-- Laureana Castanheira Rocha
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES (DEFAULT, 'Laureana Castanheira Rocha', 'whatsapp', 'lauriirocha.97@gmail.com', '351934660856', '2025-10-04', NULL, NULL, NULL, 'maos', 'Malmequeres, rosas, umas que parecem cardos e bolinhas', 'maos', 'branco', 'nao_sei', '{"options":["Fitas, tecidos ou rendas","Joia ou medalha"],"notes":""}'::jsonb, 'nao', NULL, NULL, NULL, NULL, NULL, 'casamentos_pt', NULL, NULL, 'cancelado', 300, '100_por_pagar', 0, 'na', NULL, FALSE, NULL, NULL, 'na', 'na', NULL);

-- Eugenia Sardinha
INSERT INTO orders (order_id, client_name, contact_preference, email, phone, event_date, event_type, couple_names, event_location, flower_delivery_method, flower_type, frame_delivery_method, frame_background, frame_size, extras_in_frame, extra_small_frames, extra_small_frames_qty, christmas_ornaments, christmas_ornaments_qty, necklace_pendants, necklace_pendants_qty, how_found_fbr, how_found_fbr_other, additional_notes, status, budget, payment_status, partner_commission, partner_commission_status, flower_shipping_cost, flower_shipping_paid, coupon_code, coupon_expiry, coupon_status, client_feedback_status, frame_delivery_date) VALUES (DEFAULT, 'Eugenia Sardinha', 'email', 'eugeniapatricia_99@hotmail.com', '351961738060', '2026-05-09', 'casamento', NULL, NULL, 'ctt', 'Bouquet de noiva', 'ctt', 'transparente', '40x50', '{"options":["Não pretendo incluir extras"],"notes":""}'::jsonb, 'nao', NULL, 'nao', NULL, 'nao', NULL, 'recomendacao', NULL, NULL, 'cancelado', 400, '100_por_pagar', 0, 'na', NULL, FALSE, NULL, NULL, 'na', 'na', NULL);

COMMIT;
